### ISSUE TITLE
Page Views

### ISSUE THREAD

**Issue by KateMcRo** [KateMcRo/Plantastic#32]
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39

**Comment by KateMcRo** [comment]
Figma board has been updated with web views: [Plantastic Mockups](https://www.figma.com/file/m8oHehHSpRv4UVn1XF3o66/Untitled?type=design&node-id=0-1&mode=design&t=raVNQq9QH38UweQZ-0)

**Comment by Letmego1st** [comment]
Got it Kate
