### ISSUE TITLE
Consistent Nav Bar

### ISSUE THREAD

**Issue by KateMcRo** [KateMcRo/Plantastic#33]
- [ ] Nav bar is the same across all views
- [ ] Web/mobile friendly
- [ ] Uses brand styling
- [ ] Home, My Garden, Search, (sign up, log in, log out as needed)
- [ ] Hides signup when logged in
- [ ] Shows log out when logged in

**Comment by Letmego1st** [comment]
Consistent Nav bar is active on all pages.
