### ISSUE TITLE
Home Page (logo, description, signup/login buttons)

### ISSUE THREAD

**Issue by KateMcRo** [KateMcRo/Plantastic#34]
- [ ] Logo
- [ ] Description/Tag line
- [ ] Sign Up Button
- [ ] Log In Button
- [ ] Plant image for web with other items in div to right

[Figma w/ Web details](https://www.figma.com/file/m8oHehHSpRv4UVn1XF3o66/Untitled?type=design&node-id=0-1&mode=design&t=raVNQq9QH38UweQZ-0)

**Comment by Letmego1st** [comment]
All requirements for homepage were completed.
